### PR TITLE
Better checking of USFM, TN, and all nested quotes & brackets

### PR DESCRIPTION
**Pull request by RobH123**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/41)

### CODE REVIEW

**Comment by RobH123** [comment]
Feel free to go ahead merge this after reviewing, if it's worthy, coz I'll be sleeping.

**Comment by RobH123** [comment]
Ran out of time to get all tests working again.

**Comment by PhotoNomad0** [comment]
@RobH123 - Just a tip here.  With github you can create the PR as a draft PR.  That way it cannot be merged until you click ready for review.  Also we typically prefix the PR title with `WIP: ` as a flag that it is still a work in progress as a tip not to merge.

**Comment by RobH123** [comment]
Sorry @PhotoNomad0, I've looked and looked at these failing tests and can't figure out what I messed up. Can you pls help me here -- I'm stuck.

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 1 of 25 files at r2, 2 of 3 files at r3, 11 of 26 files at r4, 53 of 53 files at r5.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
