### PR TITLE
Handle new TSV filename style; other small fixes

### PR DESCRIPTION
**Pull request by RobH123**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/155)

### CODE REVIEW

**Comment by BincyJ** [comment]
@mandolyte, @birchamp  would you know what main issue we can connect this PR to?

**Comment by BincyJ** [comment]
This is a 2.0.0 issue

**Comment by BincyJ** [comment]
@birchamp can we take the 1.2 tag from this PR?

**Comment by RobH123** [comment]
@mandolyte Could you please look at this PR before I start on the next round of content publishing. Thanks.

**Review by mandolyte — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 35 of 35 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/155)* status: all files reviewed, 1 unresolved discussion (waiting on @RobH123)

___
*[src/core/defaults.js, line 7 at r2](https://reviewable.io/reviews/unfoldingword/uw-content-validation/155#-MXg7_zkDVrqZxAQdL7m:-MXg7_zkDVrqZxAQdL7n:bgsneds) ([raw file](https://github.com/unfoldingword/uw-content-validation/blob/5268098400f9c893a9620b9051f15537d5747e28/src/core/defaults.js#L7)):*
> ```JavaScript
>   'LT', 'ST',
>   'TA', 'TW', 'TWL',
>   'TN', 'TN2', 'TQ', 'TQ2',
> ```

are still going to need the "...2" repo codes now?

**Review by mandolyte — APPROVED** [review]

**Comment by RobH123** [comment]
@mandolyte We still need to distinguish between the old and new TN and TQ formats for validation I think. Maybe for the longer term, TN should be TN1, then TN2 could be just TN, and similarly for TQ? It's going to be tricky, I think, over the next year or so as things change around, and I still expect many changes to this CV package as various tool and content migration decisions are made one by one.

**Pull request merged**
