### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by RobH123**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/217)

### CODE REVIEW

**Comment by RobH123** [comment]
Still more work for me to do of course @mandolyte, but I imagine you probably want to start using these fixes for OBS-TN/TQ/SN/SQ repos, plus a few other small improvements.

**Comment by mandolyte** [comment]
The first option sounds good, same function with bookid set to OBS. Thanks!

**Comment by RobH123** [comment]
Ok @mandolyte, I think this could be ready to go now -- see if those [wrappers](https://github.com/unfoldingWord/uw-content-validation/blob/new.2021.September.5/src/core/wrapper.js) should do what you want. (I did add the filename/filepath fields back in, as they enable the package to suppress known non-errors for particular files.)

**Comment by RobH123** [comment]
@mandolyte We probably should see if this can be merged so we can get to v3. I'm not sure who's waiting on who here? (Meanwhile, I've [moved on](https://github.com/unfoldingWord/uw-content-validation/pull/229).)

**Review by mandolyte — COMMENTED** [review]
> Reviewed 9 of 14 files at r4, 25 of 25 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/217)* status: all files reviewed, 1 unresolved discussion (waiting on @RobH123)

**Review by mandolyte — APPROVED** [review]

**Pull request merged**
