### PR TITLE
New version with changed API for updated TSV formats

### PR DESCRIPTION
**Pull request by RobH123**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/147)

### CODE REVIEW

**Comment by mandolyte** [comment]
@RobH123 Could you connect this PR with an issue please? Our QA practices have standardized on this so that they and I as a reviewer have context and understanding of the changes.

I see this is still in draft mode, but I also wanted to ask whether this code would automatically detect whether a resource was in the new TSV format or not... in other words, will this be a breaking change that we have to coordinate deployment with the data format change.

Thanks!

**Comment by RobH123** [comment]
> Could you connect this PR with an issue please? Our QA practices have standardized on this so that they and I as a reviewer have context and understanding of the changes.

@mandolyte There were already six linked issues and I just added another one. I apologise from the ongoingness of this PR -- it's partly coz the new TSV formats were only finally approved yesterday, and partly because of how I work -- flitting back and forth from publishing/content work to software development and adding/fine-tuning checks as I understand the need for them during the publishing. Also partly coz I hadn't been able to devote a big-enough block of time to thorough testing of the new format checks.

**Comment by RobH123** [comment]
I see this is still in draft mode, but I also wanted to ask whether this code would automatically detect whether a resource was in the new TSV format or not... in other words, will this be a breaking change that we have to coordinate deployment with the data format change.

@mandolyte This big change is certainly a breaking change to the APIs (as reflected in the title and version number). That's partly why I wanted to also work on some issues/improvements that had been waiting for a break.

As to implementation of new formats in tC Create and your BP apps, I don't think that the roll-out has been fully planned yet. But here in general, each different TSV format has a different checking function. For the demos, I choose the formats [here](https://github.com/unfoldingWord/uw-content-validation/blob/RJHimprovements/src/demos/book-package-check/checkBookPackage.js#L319) where TN2 and TQ2 and TWL will each cause the [new checking functions to be called](https://github.com/unfoldingWord/uw-content-validation/blob/master/src/demos/book-package-check/checkBookPackage.js#L300).

**Comment by RobH123** [comment]
I think this is finally working good enough to be a first attempt at v2

**Review by mandolyte — APPROVED** [review]
> Reviewed 56 of 84 files at r2, 30 of 30 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/147)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
