### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by RobH123**
Closing manifest file errors

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/113)

### CODE REVIEW

**Comment by mandolyte** [comment]
Since these functions use a straight parameter list, username is not optional. If this is a breaking change, you should make this part of a 1.0.0 (or 1.0.0-alpha1) release.

**Comment by ancientTexts-net** [comment]
___
*[src/demos/file-check/checkFileContents.js, line 74 at r2](https://reviewable.io/reviews/unfoldingword/uw-content-validation/113#-MQGPCHv6Ho4MlDA2LBu:-MQGPCHwCVapUS0CsucW:b-3yu9s4) ([raw file](https://github.com/unfoldingword/uw-content-validation/blob/2907578321c9aa64a71f56c2ee3b7e88b9004ee7/src/demos/file-check/checkFileContents.js#L74)):*
> ```JavaScript
>     checkFileResult = checkPlainText('text', filename, fileContent, ourCFLocation, checkingOptions);
>   else if (filenameLower === 'manifest.yaml')
>     // TODO: Does the branch need to be passed in as a parameter???
> ```

@robh123  @mandolyte 

Do we need to resolve this TODO before merging?
What do you think?

Thanks

**Review by ancientTexts-net — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/113)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net and @RobH123)

**Comment by ancientTexts-net** [comment]
___
*[src/demos/notice-processing-functions.js, line 106 at r3](https://reviewable.io/reviews/unfoldingword/uw-content-validation/113#-MQIEAMHBdxbF6gooYmV:-MQIEAMHBdxbF6gooYmW:b2nh8oq) ([raw file](https://github.com/unfoldingword/uw-content-validation/blob/81f716ca39f197e4aeb01adaf64de2515ce7d300/src/demos/notice-processing-functions.js#L106)):*
> ```JavaScript
>     // It only really makes sense if the debugChain is enabled
>     if (givenNoticeObject.noticeList && givenNoticeObject.noticeList.length)
>         if (givenNoticeObject.noticeList.length > 8000)
> ```

???

**Review by ancientTexts-net — COMMENTED** [review]
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/uw-content-validation/113)* status: all files reviewed, 1 unresolved discussion (waiting on @RobH123)

**Review by ancientTexts-net — APPROVED** [review]

**Pull request merged**
